/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02.iu;

import javax.swing.JOptionPane;
import trabalho02.controlador.Controlador;

/**
 *
 * @author Erick Yoshike
 */
public class CadastroLivros extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivros
     */
    public CadastroLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeL = new javax.swing.JTextField();
        txtIDL = new javax.swing.JTextField();
        txtAnoL = new javax.swing.JTextField();
        btnSalvarL = new javax.swing.JButton();
        btnLimparL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("ID");

        jLabel3.setText("Ano");

        txtNomeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeLActionPerformed(evt);
            }
        });

        txtIDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDLActionPerformed(evt);
            }
        });

        txtAnoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoLActionPerformed(evt);
            }
        });

        btnSalvarL.setText("Salvar");
        btnSalvarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLActionPerformed(evt);
            }
        });

        btnLimparL.setText("Limpar");
        btnLimparL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimparL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btnSalvarL))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeL, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtIDL)
                            .addComponent(txtAnoL))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAnoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarL)
                    .addComponent(btnLimparL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLActionPerformed
        if (txtNomeL.getText() == null || txtNomeL.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o nome do livro antes de salvar!!");
            txtNomeL.requestFocus();
        } else if (txtIDL.getText() == null || txtIDL.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o ID do livro antes de salvar!!");
            txtIDL.requestFocus();
        } else if (txtAnoL.getText() == null || txtAnoL.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o ano do livro antes de salvar!!");
            txtAnoL.requestFocus();
        } else {
            Controlador control = new Controlador();
            control.addLivro(txtIDL.getText(), txtNomeL.getText(),
                    Integer.parseInt(txtAnoL.getText()));
            JOptionPane.showMessageDialog(this, "Salvo com sucesso");
            txtNomeL.setText("");
            txtIDL.setText("");
            txtAnoL.setText("");
            txtNomeL.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarLActionPerformed

    private void btnLimparLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparLActionPerformed
        txtNomeL.setText("");
        txtIDL.setText("");
        txtAnoL.setText("");
        txtNomeL.requestFocus();
    }//GEN-LAST:event_btnLimparLActionPerformed

    private void txtNomeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeLActionPerformed

    private void txtIDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDLActionPerformed

    private void txtAnoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparL;
    private javax.swing.JButton btnSalvarL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAnoL;
    private javax.swing.JTextField txtIDL;
    private javax.swing.JTextField txtNomeL;
    // End of variables declaration//GEN-END:variables
}
