/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02.iu;

import java.util.ArrayList;
import trabalho02.modelo.Biblioteca;
import trabalho02.modelo.Livro;
import trabalho02.modelo.Emprestimo;
import trabalho02.modelo.Item;
/**
 *
 * @author Erick Yoshike and now Luskas
 */
public class RelatorioLivrosEmprestadosUsuario extends javax.swing.JFrame {
    Biblioteca b = Biblioteca.getInstance();
    Emprestimo e = Emprestimo.getInstance();

        ArrayList<Emprestimo>emprestimos = b.getEmprestimos();
        ArrayList<Item>itens;
        ArrayList<Livro>livros = b.getLivros();
    /**
     * Creates new form RelatorioTodosUsuarios
     */
    public RelatorioLivrosEmprestadosUsuario() {
        initComponents();
        
        

        for (Emprestimo e1: emprestimos) {
            itens = e1.getItens();
            for (Item i : itens) {
                i.getCodLivro();
                
            }
            if (l.estaEmprestado()) {
                jTextArea1.append("Código do livro: " + l.getCodLivro()
                    + "\nNome do livro: " + l.getNome()
                    + "\nAno do livro: " + l.getAno()
                    + "\n\n\n----------------------------------------------------"
                    + "-------------------------------------------------"
                    + "--------\n");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioLivrosEmprestadosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
