/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02.iu;
import javax.swing.JOptionPane;
import trabalho02.modelo.Biblioteca;
import trabalho02.modelo.Usuario;
import trabalho02.dados.Database;
import trabalho02.modelo.Professor;
import trabalho02.modelo.Emprestimo;
/**
 *
 * @author Guga
 */
public class RelatorioProfessor extends javax.swing.JFrame {
  Database db = Database.getInstance();
    Usuario u[] = db.getUsuarios();
     Emprestimo e[]= db.getEmprestimos();
       int j;
    /**
     * Creates new form RelatorioProfessor
     */
    public RelatorioProfessor() {
        initComponents();
        
       
      
        for(int i = 0; i< db.getContU(); i++){
            if  (u[i] instanceof Professor){
                cbNome.addItem(u[i].getNome()); 
            }
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNome = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbNome.setToolTipText(",");
        cbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        txtDados.setColumns(20);
        txtDados.setRows(5);
        jScrollPane2.setViewportView(txtDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeActionPerformed
           txtDados.append( "Nome \t ID \t Titulação\t Emprestimo \t Atraso\n\n\n" );
      
        for(int i = 0; i< db.getContU(); i++){
     
        if (((String)cbNome.getSelectedItem()).equals(u[i].getNome())){
            j =db.getContE();
           if(j !=0){
               for(int j =0; j<db.getContE();j++){
                if(u[i].getCodUsuario() == e[j].getCodUsuario()){
                     txtDados.append( u[i].getNome() + "\t" 
                               + u[i].getCodUsuario() + "\t"
                               + ((Professor)u[i]).getTitulacao()+ "\t"
                               + "Sim \t"
                               + "Sim \n"
                               + "---------------------------------------------------------------------------------------\n\n");
                 }
            
              
                else { 
                    txtDados.append( u[i].getNome() + "\t" 
                               + u[i].getCodUsuario() + "\t"
                               + ((Professor)u[i]).getTitulacao()+ "\t"
                               + "Não \t"
                               + "Não \n"
                               + "----------------------------------------------------------------------------------------\n\n");
                   }
                }   
             }
              else { 
                    txtDados.append( u[i].getNome() + "\t" 
                               + u[i].getCodUsuario() + "\t"
                               + ((Professor)u[i]).getTitulacao()+ "\t"
                               + "Não \t"
                               + "Não \n"
                               + "----------------------------------------------------------------------------------------\n\n");
                }
            
             }
        }   
    }//GEN-LAST:event_cbNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDados;
    // End of variables declaration//GEN-END:variables
}
